logging:
  level:
    com.zxchange: DEBUG

server:
  port: 8080

spring:
  datasource:
    url: jdbc:sqlite:./zxchange.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true

zxchange:
  finnhub:
    base-url: https://finnhub.io/api/v1
    ws-url: wss://ws.finnhub.io

